### ISSUE TITLE
add `@primate/native`

### ISSUE THREAD

**Issue by ralyodio** [primatejs/primate#104]
ideally we could share the codebase between desktop and web based apps.

**Comment by ralyodio** [comment]
https://electron-vite.org/

**Comment by terrablue** [comment]
Currently tracking the [native](https://github.com/primatejs/primate/tree/native) branch.

**Comment by terrablue** [comment]
A prototype is basically done, we're missing the ability to actually package an app.

Here is the current state of the ecosystem:

* Node - https://nodejs.org/api/single-executable-applications.html ("The single executable application feature currently only supports running a single embedded script using the CommonJS module system") - currently unusable. We're using ESM, and need more than a "single embedded script".
* Deno - https://docs.deno.com/runtime/manual/tools/compiler currently fails when using `node-gtk`, see https://github.com/denoland/deno/issues/23700
* Bun - https://bun.sh/docs/bundler/executables currently fails when using `node-gtk`, see https://github.com/oven-sh/bun/issues/4290#issuecomment-2094803841

**Comment by ralyodio** [comment]
waiting to test. let us know when those issues are fixed.

**Comment by ralyodio** [comment]
terminal kit doesn't support esm either, but you can do something like this:

```
import tk from 'terminal-kit';
const term = tk.terminal;
```

**Comment by terrablue** [comment]
progress tracker

* frontend
  * [ ] angular
  * [ ] eta
  * [ ] handlebars
  * [ ] htmx
  * [ ] markdown
  * [ ] marko
  * [ ] react
  * [ ] solid
  * [ ] svelte
  * [ ] vue
  * [ ] webc

* store
  * [ ] json
  * [ ] memory
  * [ ] mongodb (requires server)
  * [ ] mysql (requires server)
  * [ ] postgresql (requires server)
  * [ ] sqlite
  * [ ] surrealdb

* binding
  * [ ] go
  * [ ] python
  * [ ] ruby
  * [ ] typescript

* misc
  * [ ] types
  * [ ] session 
  * [ ] i18n

* todos
  * [ ] copy `node_modules` to build directory
