### ISSUE TITLE
add `@primate/style`

### ISSUE THREAD

**Issue by terrablue** [primatejs/primate#139]
Support for

* Tailwind (mostly integrating into the build system, e.g.):
```js
export default {
  content: ["./components/**/*.svelte"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

And then programmatically running ` npx tailwindcss -i ./static/*.css -o ./static/*.css --watch` or so.

* others?

**Comment by ralyodio** [comment]
this would be cool to add more than just tailwind

**Comment by terrablue** [comment]
https://github.com/primatejs/primate/issues/165
