### ISSUE TITLE
release 0.32: acceptance criteria

### ISSUE THREAD

**Issue by terrablue** [primatejs/primate#147]
To prevent regressions, a release will be blocked until the following regression criteria have been accepted.

* frontend
  * angular
    * [x] ssr
    * [x] props
  * handlebars
    * [x] ssr
    * [x] props
  * htmx
    * [x] csr
    * [x] props
    * [x]  extensions
  * markdown
    * [x] ssr
  * marko
    * [x] ssr
    * [x] props
  * react
    * [x] ssr
    * [x] csr
    * [x] props
    * [x] spa GET (browsing using fetch)
    * [x] spa POST (submitting forms via fetch)
    * [x] <Head> element
    * [x] i18n translations
    * [x] i18n locale switching
    * [x] layouts
    * [x] recursive layouts
  * solid
    * [x] ssr
    * [x] csr
    * [x] props
    * [x] spa GET (browsing using fetch)
    * [x] spa POST (submitting forms via fetch)
    * [x] <Head> element
    * [x] i18n translations
    * [x] i18n locale switching
    * [x] layouts
    * [x] recursive layouts
  * svelte
    * [x] ssr
    * [x] csr
    * [x] props
    * [x] spa GET (browsing using fetch)
    * [x] spa POST (submitting forms via fetch)
    * [x] i18n translations
    * [x] i18n locale switching
    * [x] layouts
    * [x] recursive layouts
  * vue
    * [x] ssr
    * [x] props
  * webc
    * [x] csr
    * [x] props

* store
  * memory
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions
  * json
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions
  * mongodb
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions
  * mysql
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions
  * postgresql
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions
  * sqlite
     * [ ] get
     * [ ] find
     * [ ] insert
     * [ ] update
     * [ ] delete
     * [ ] custom actions
  * surrealdb
     * [x] get
     * [x] find
     * [x] insert
     * [x] update
     * [x] delete
     * [x] custom actions

* binding
  * go
    * [x] plain text
    * [x] json
    * [x] view
    * [x] redirect
  * python
    * [x] plain text
    * [x] json
    * [x] view
    * [x] redirect
  * ruby
    * [x] plain text
    * [x] json
    * [x] view
    * [x] redirect
  * typescript
    * [x] plain text
    * [x] json
    * [x] view
    * [x] redirect

* misc
  * session 
    * [x] create
    * [x] update
    * [x] delete
  * guards
    * [x] normal
    * [x] recursive 
  * routes
    * [x] disable body parsing per route `export const body = { parse: false }`
    * [x] query string decodes params
  * handlers
    * view
      * [x] partial rendering (`{ partial: true }`)

**Comment by ralyodio** [comment]
LGTM
