### ISSUE TITLE
drop `@primate/ws` and replace with a `ws` and a `sse` handler

### ISSUE THREAD

**Issue by terrablue** [primatejs/primate#44]
WebSocket support is to be moved to the runtime, which will also have support for SSE.

Drop the `@primate/ws` package in favor of two handlers in core, `ws` and `sse`.

See also https://github.com/rcompat/rcompat/issues/1

**Comment by ralyodio** [comment]
cool

**Comment by terrablue** [comment]
@primate/ws dropped in [9a1a00e](https://github.com/primatejs/primate/commit/9a1a00ea873caae7d7367c9c056ebee1f2c0ec54)

**Comment by terrablue** [comment]
sse support added in https://github.com/primatejs/primate/commit/e5be636e3c56563e6d7e17db472daab02ac11896, ws finalized in https://github.com/primatejs/primate/commit/9eabc05247aa6356226be9e52776f56d8358a2c2
