### ISSUE TITLE
support web components as frontend framework

### ISSUE THREAD

**Issue by ralyodio** [primatejs/primate#53]
I don't know if its possible to do ssr with web components, but it would be nice to support native web components.

**Comment by ralyodio** [comment]
https://lit.dev/docs/ssr/overview/

**Comment by terrablue** [comment]
Initial support added in https://github.com/primatejs/primate/commit/089c9e35c9b5364e2ff5a4f01a8a06d2d3cd02eb.

To do / missing:
* [ ]  SSR / Hydration
* [ ]  Slotting / layouts
* [ ]  Head Component?

**Comment by ralyodio** [comment]
```
 window.addEventListener('beforeunload', () => {
   console.log('Clicked browser back button');
 });
```

**Comment by terrablue** [comment]
no current activity on this, can reopen if becomes relevant again
