### ISSUE TITLE
decide on a path parameter style in filesystem-based routes

### ISSUE THREAD

**Issue by terrablue** [primatejs/primate#69]
Following the chat discussion, it appears `[]` isn't a universal standard for path parameters, though it is widely used by Next, Nuxt and SvelteKit. Remix uses `$`.

### Normal
Matches anything between two slashes. If the route file is `post/ID.js` and `ID` is the placeholder, then `/post/1`, `post/2` and `post/one` are matched and made available as `{ ID: "1" }`,`{ ID: "2" }` respectively `{ ID: "one" }` to the backend.

Use case: making a part of the path dynamic, like a user id.

### Optional
Optionally matches anything between two slashes. If the route file is `LANG/post.js` and `LANG` is the optional placeholder, then `/post`, `/de/post`, `/anything/post` are matched and made available as `{ LANG: undefined }`, `{ LANG: "de" }` respectively `{ LANG: "anything" }` to the backend.

Use case: making a part of the path dynamic but keeping it optional, to allow fallback to default, like application language.

### Rest/catch-all
Greedily matches anything from a slash until end. Can only appear at the end of routes. If the route file is `browse/REST.js` and `REST` is the rest placeholder, then `/browse/1`, `/browse/1/2`, `/browse/one/two/three` are matched and made available as `{ REST: "1" }`, `{ REST: "1/2" }` respectively  `{ REST: "one/two/three" }` to the backend.

Use case: matching subpaths, such as when browsing a documentation website. For example, in `https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100`, `Web/HTTP/Status/100` is a subpath.

### Optional rest
Optionally greedily matches anything from a slash until end. Can only appear at the end of routes. If the route file is `browse/OPTIONAL_REST.js` and `OPTIONAL_REST` is the rest placeholder, then `/browse`, `/browse/1/2`, `/browse/one/two/three` are matched and made available as `{ OPTIONAL_REST: undefined }`, `{ OPTIONAL_REST: "1/2" }` respectively  `{ OPTIONAL_REST: "one/two/three" }` to the backend. 

Use case: matching subpaths where the subpath can be missing completely.

### Typed
In addition, some frameworks like SvelteKit support runtime checks of path parameters. If the route file is `post/ID=NUMBER.js` and `ID` is the placeholder, then `/post/1`, `post/2` but NOT `post/one` are matched and made available as `{ ID: "1" }` respectively `{ ID: "2" }`  to the backend. Some frameworks like Primate also automatically coerce those parameters, such that in this example they are made available as `{ ID: 1 }` respectively `{ ID: 2 }`.

Use case: making a part of the path dynamic, like a user id, but only if it fulfills a type predicate.

## How other frameworks denote path parameters

|Type|[Next]|[Nuxt]|[Sveltekit]|[Remix]|[Analog]|[Primate]|
|-------|---------|---------|--------------|-----------|-------------|-------------|
|Normal|[param]|[param]|[param]|$param|[param]|{param}|
|Optional|[TODO](https://github.com/vercel/next.js/discussions/15526)|[[param]]|[[param]]|(param)|?|TODO|
|Rest/catch-all|[...param]|[...param]|[...param]|?|[...param]|TODO|
|Optional rest|[[...param]]|?|?|?|?|TODO|
|Typed|?|?|[param=number]|?|?|{param=number}|

## Option 1

While no framework implements this fully at the moment, a consensus (similar to Next/Nuxt/SvelteKit) could be:
* `[param]` for normal
* `[[param]]` for optional
* `[...param]` for rest
* `[[...param]]` for optional rest

All potentially typed.

Advantage: would be natively parseable by [FileSystemRouter](https://bun.sh/docs/api/file-system-router) in Bun, if it is extended to support non-rest optionals.

## Option 2

An alternative brought up in the chat would be:

* `{param}` for normal
* `[param]` for optional
* `{...param}` for rest
* `[...param]` for optional rest

All potentially typed.

**Can we get a show of hands which variant has more support, or alternative suggestions?**

[Next]: https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes
[Nuxt]: https://nuxt.com/docs/guide/directory-structure/pages
[SvelteKit]: https://kit.svelte.dev/docs/advanced-routing
[Remix]: https://remix.run/docs/en/main/discussion/routes
[Analog]: https://analogjs.org/docs/features/routing/overview
[Primate]: https://primatejs.com/guide/routes

**Comment by ralyodio** [comment]
I'm not clear on the difference between REST and OPTIONAL REST.

**Comment by terrablue** [comment]
browse/REST.js -> matches `/browse/1`, `/browse/1/2`, `/browse/one/two/three`, but NOT `/browse` (`/` must appear in subpath)
browse/OPTIONAL_REST.js -> matches `/browse`, `browse/1`, `/browse/1/2`, `/browse/one/two/three`, (`/` can appear in subpath)

**Comment by ralyodio** [comment]
gotcha

**Comment by terrablue** [comment]
Will be going with option 1.

**Comment by terrablue** [comment]
done in [fc47845](https://github.com/primatejs/primate/commit/fc47845f9e2b02a46ed7373deb1ef6bfb82cbf6d)
