### ISSUE TITLE
add Marko js support 

### ISSUE THREAD

**Issue by alphaelf** [primatejs/primate#71]
[Marko](https://markojs.com/ ) js is fast and powerful template language

**Comment by terrablue** [comment]
Hi, thanks. Common (SSR) support added in [80ad0d7](https://github.com/primatejs/primate/commit/80ad0d7022d3f5be909419524cb9afd7cc097241) and will be part of 0.29, which should be out by the 18th.

Until 0.29 is out, docs are available at https://github.com/primatejs/primate/blob/docs-0.29/docs/modules/marko.md

If you need hydration / other features (see [Support matrix](https://github.com/primatejs/primate/blob/docs-0.29/docs/modules/frontend.md#support-matrix)), please request them here.
