### ISSUE TITLE
Routes marked as invalid on Windows due to path resolution

### ISSUE THREAD

**Issue by Daniel-Ozori** [primatejs/primate#98]
Routes are marked as invalid on windows because of how the paths are resolved.
`!! primate invalid path a\[alias]
++ use only letters, digits, '_', '[', ']' or '=' in path filenames`.

Paths are resolved using backslashes on windows. An invalid character

**Comment by terrablue** [comment]
Hi, thanks for the bug report. Could you please try again with the newly released `0.30.2`?

**Comment by Daniel-Ozori** [comment]
Hello, It works now. Thanks

**Comment by phaleth** [comment]
thanks for the feedback. @Daniel-Ozori
